---
# tasks file for docker-ansible
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

    # Set up Docker repository
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
- name: Install Docker CE and dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

    # Add the user to the Docker group
- name: Add user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

    # Install Docker Compose
- name: Download Docker Compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

    # Verify Docker Compose installation
- name: Verify Docker Compose installation
  command: docker-compose --version
  register: docker_compose_version
  ignore_errors: yes

- name: Print Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout | default('Not installed') }}"
